'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number(n||0).toLocaleString('ko-KR')+'원';
const boxCount=row=>row.carrier==='대신'?Math.ceil(Number(row.qty)||0):Number(row.qty)||0;
const day=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const today=day(), dayLabel=d=>d.replaceAll('-','. ')+'.', key='sanghwa-registration-demo-v1';
const field=(form,name)=>form.elements.namedItem(name);
const initial=()=>({day:today,serial:2,rows:[
 {id:'d1',carrier:'대신',date:today,receiver:'테스트상사(광양)',sender:'테스트 발화주',phone:'00000000000',address:'광양 테스트영업소',postal:'12345',qty:1,fare:5500,pay:'착불',delivery:'정기',status:'ready',waybill:'',pda:false,done:false,prints:0},
 {id:'d2',carrier:'대신',date:today,receiver:'테스트부품(서천)',sender:'테스트 발화주',phone:'00000000000',address:'충남 서천군 테스트로 10',postal:'12345',qty:0.5,fare:6600,pay:'선불',delivery:'택배',status:'ready',waybill:'',pda:false,done:false,prints:0},
 {id:'d3',carrier:'대신',date:today,receiver:'테스트모터스(주소확인)',sender:'테스트 발화주',phone:'00000000000',address:'경기 수원시 테스트로 20',postal:'',qty:1,fare:7150,pay:'착불',delivery:'택배',status:'ready',waybill:'',pda:false,done:false,prints:0},
 {id:'d4',carrier:'대신',date:today,receiver:'테스트오토(등록완료)',sender:'테스트 발화주',phone:'00000000000',address:'수원 테스트영업소',postal:'12345',qty:2,fare:11000,pay:'착불',delivery:'정기',status:'registered',waybill:'DEMO-DS-0001',pda:false,done:false,prints:0},
 {id:'l1',carrier:'로젠',date:today,receiver:'테스트카센터(착불)',sender:'테스트 발화주',phone:'00000000000',address:'서울 테스트로 30',postal:'12345',qty:1,fare:3500,pay:'착불',delivery:'택배',status:'registered',waybill:'DEMO-LG-0001',pda:false,done:false,prints:0},
 {id:'l2',carrier:'로젠',date:today,receiver:'테스트정비(제주 선불)',sender:'테스트 발화주',phone:'00000000000',address:'제주특별자치도 제주시 테스트로 40',postal:'12345',qty:1,fare:6300,pay:'선불',delivery:'택배',status:'ready',waybill:'',pda:false,done:false,prints:0}
],registrationLog:[],printLog:[]});
let state=initial();
try{const saved=JSON.parse(localStorage.getItem(key)||'null');if(saved?.day===today&&Array.isArray(saved.rows)&&Array.isArray(saved.registrationLog)&&Array.isArray(saved.printLog)&&Number.isInteger(saved.serial))state=saved;}catch{}
for(const row of state.rows){if(row.status==='running')row.status='uncertain';row.waybillChecked??=!!row.done;}
let tab='list',carrier='전체',newCarrier='대신',selected=new Set(['d1','d2']),from=today,to=today,busy=false,reviewIds=[],returnToReview=false,confirmResolve=null,toastTimer;
const persist=()=>{try{localStorage.setItem(key,JSON.stringify(state));}catch{}};
const find=id=>state.rows.find(row=>row.id===id);
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>{$('#toast').hidden=true;},4400);}
function validate(row){if(!row.receiver.trim())return '수화주명 확인';if(!row.address.trim())return '주소 / 영업소 확인';if(!/^\d{5}$/.test(row.postal))return '우편번호 확인';if(!(Number(row.qty)>0))return '수량 확인';return '';}
function visible(){const query=$('#search').value.trim().toLowerCase(),status=$('#status-filter').value;return state.rows.filter(r=>r.date>=from&&r.date<=to&&(carrier==='전체'||r.carrier===carrier)&&(status==='all'||r.status===status)&&(!query||[r.receiver,r.sender,r.waybill].some(v=>v.toLowerCase().includes(query))));}
function statusHtml(row){if(row.status==='registered')return '<span class="pill success">등록완료</span>';if(row.status==='uncertain')return '<span class="pill wait">결과 확인 필요</span><button class="status-recheck" data-reconcile="'+row.id+'">등록 결과 확인</button>';if(row.status==='running')return '<span class="pill">등록 중…</span>';return validate(row)?'<span class="pill error">정보확인</span>':'<span class="pill">미등록</span>';}
function renderList(){
 const rows=visible();
 $('#period-label').textContent='▦ 조회기간: '+dayLabel(from)+(from===to?'':' ~ '+dayLabel(to));
 $('#shipment-body').innerHTML=rows.length?rows.map(r=>`<tr data-row="${escapeHtml(r.id)}" class="${selected.has(r.id)?'selected':''} ${r.pda&&r.waybillChecked&&r.done?'checklist-done':''}"><td><input type="checkbox" data-select="${escapeHtml(r.id)}" aria-label="${escapeHtml(r.receiver)} 선택" ${selected.has(r.id)?'checked':''}></td><td class="shipment-date">${escapeHtml(dayLabel(r.date))}</td><td class="company-cell"><button class="company-name" data-edit="${escapeHtml(r.id)}">${escapeHtml(r.receiver)}</button><div class="registration-status">${statusHtml(r)}</div>${r.waybill?`<div class="waybill">테스트 송장번호 · ${escapeHtml(r.waybill)}</div>`:validate(r)?`<div class="waybill error-text">${escapeHtml(validate(r))} · 업체명을 눌러 수정</div>`:''}</td><td>${r.pay}</td><td><span class="carrier-tag ${r.carrier==='로젠'?'logen':''}">${r.carrier}</span>${r.delivery==='정기'?'화물':r.delivery}</td><td>${boxCount(r)}박스</td><td class="numeric">${money(r.fare)}</td><td class="check-start"><button class="row-check-all" data-check-row="${escapeHtml(r.id)}">전체</button></td><td><input type="checkbox" data-pda="${escapeHtml(r.id)}" aria-label="${escapeHtml(r.receiver)} PDA" ${r.pda?'checked':''}></td><td><input type="checkbox" data-waybill="${escapeHtml(r.id)}" aria-label="${escapeHtml(r.receiver)} 운송장" ${r.waybillChecked?'checked':''}></td><td><input type="checkbox" data-done="${escapeHtml(r.id)}" aria-label="${escapeHtml(r.receiver)} 종결완료" ${r.done?'checked':''}></td><td><span class="warning-mark" title="${escapeHtml(validate(r)||(!r.waybill?'발송데이터 미연결':''))}">${validate(r)||!r.waybill?'!':''}</span></td><td><button class="delete-row" data-delete="${escapeHtml(r.id)}">삭제</button></td></tr>`).join(''):'<tr><td colspan="13" class="empty">조회된 출고건이 없습니다. 날짜나 검색조건을 확인해 주세요.</td></tr>';
 const selectedVisible=rows.filter(r=>selected.has(r.id));
 $('#select-all').checked=rows.length>0&&selectedVisible.length===rows.length;$('#select-all').indeterminate=selectedVisible.length>0&&selectedVisible.length<rows.length;
 $('#selection-count').textContent='선택 '+selectedVisible.length+'건';$('#list-count').textContent='건수: '+rows.length+'건　 총수량: '+rows.reduce((sum,r)=>sum+boxCount(r),0)+'박스';
 $('#register-open').disabled=carrier==='로젠'||busy;
 $('#select-ready').hidden=carrier==='로젠';
 $('#action-hint').textContent=carrier==='로젠'?'로젠 자동등록은 API 승인 후 연결 예정입니다. PDA 출력 요청은 등록완료 샘플로 테스트할 수 있습니다.':'출고건을 선택한 뒤 ‘대신 전산 등록’을 눌러보세요. 파일 다운로드 없이 등록하는 흐름입니다.';
 $$('.carrier-tabs [data-carrier]').forEach(b=>b.classList.toggle('active',b.dataset.carrier===carrier));
 $('.nav').classList.toggle('logen',carrier==='로젠');
}
function renderLogs(){
 $('#summary-cards').innerHTML=[['샘플 출고',state.rows.length],['전산등록 완료',state.rows.filter(r=>r.status==='registered').length],['결과 확인 필요',state.rows.filter(r=>r.status==='uncertain').length],['출력 요청',state.printLog.length]].map(([label,value])=>`<div class="summary-card"><span>${label}</span><strong>${value}건</strong></div>`).join('');
 $('#print-log').innerHTML=state.printLog.length?[...state.printLog].reverse().map(log=>`<div class="log-item"><div><strong>${escapeHtml(log.receiver)}</strong> <span class="pill success">${log.reprint?'재출력 요청':'출력 요청'}</span><p>${escapeHtml(log.carrier)} · ${escapeHtml(log.waybill)} · ${log.carrier==='대신'?'BIXOLON':'PS100'} (모의 출력)</p></div><time>${escapeHtml(log.time)}</time></div>`).join(''):'<p class="empty">아직 출력 요청이 없습니다. 출고목록에서 등록완료 건의 PDA를 체크해 보세요.</p>';
 $('#registration-log').innerHTML=state.registrationLog.length?[...state.registrationLog].reverse().map(log=>`<div class="log-item"><div><strong>${escapeHtml(log.text)}</strong><p>${escapeHtml(log.names)}</p></div><time>${escapeHtml(log.time)}</time></div>`).join(''):'<p class="empty">아직 전산등록 테스트 기록이 없습니다.</p>';
 $('#master-list').innerHTML=state.rows.map(r=>`<div class="master-card"><strong>${escapeHtml(r.receiver)}</strong> <span class="pill">${r.carrier}</span><p>${escapeHtml(r.address)}<br>우편번호 ${escapeHtml(r.postal||'미입력')}</p></div>`).join('');
}
function render(){renderList();renderLogs();persist();}
function navigate(next){tab=next;$$('.nav [data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===next);if(b.dataset.tab===next)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});['new','list','verify','master'].forEach(id=>{$('#'+id+'-view').hidden=id!==next;});if(next==='list'){from=to=today;$('#from-date').value=$('#to-date').value=today;renderList();}$('.nav').classList.toggle('logen',next==='new'?newCarrier==='로젠':carrier==='로젠');if(next==='verify'||next==='master')renderLogs();}
function selectionForRegistration(){return visible().filter(r=>selected.has(r.id));}
function openRegistration(){const all=selectionForRegistration();reviewIds=all.filter(r=>r.carrier==='대신'&&r.status==='ready').map(r=>r.id);if(!reviewIds.length){toast(all.some(r=>r.status==='uncertain')?'결과 확인이 필요한 건은 ‘등록 결과 확인’을 먼저 눌러 주세요.':'등록할 미등록 대신 출고건을 선택해 주세요. 등록완료 건은 중복 등록하지 않습니다.');return;}renderReview(all.length-reviewIds.length);$('#register-dialog').showModal();}
function renderReview(skipped=0){const rows=reviewIds.map(find).filter(Boolean),invalid=rows.filter(validate);$('#register-title').textContent='등록할 출고건을 확인해 주세요';$('#register-content').innerHTML=`<div class="modal-content"><div class="review-summary"><div><span>대신 등록대상</span><strong>${rows.length}건</strong></div><div><span>총 수량</span><strong>${rows.reduce((s,r)=>s+boxCount(r),0)}박스</strong></div><div><span>총 운임</span><strong>${money(rows.reduce((s,r)=>s+Number(r.fare),0))}</strong></div></div><div class="connection"><i class="dot"></i>테스트 연결 준비됨 · 실제 대신 전산으로 전송하지 않습니다.</div>${skipped?`<p class="muted">등록완료 건 또는 로젠 ${skipped}건은 이번 등록에서 제외했습니다.</p>`:''}${invalid.length?`<div class="warning">정보확인이 필요한 ${invalid.length}건이 있습니다. 아래 ‘수정’을 눌러 보완해 주세요.</div>`:''}${rows.map(r=>`<div class="review-row"><div><strong>${escapeHtml(r.receiver)}</strong><p>${r.delivery} · ${r.pay} · ${boxCount(r)}박스 · ${escapeHtml(r.address)}</p>${validate(r)?`<p>${escapeHtml(validate(r))} <button class="tiny" data-review-edit="${r.id}">수정</button></p>`:''}</div><div class="numeric">${money(r.fare)}<p>${validate(r)?'정보확인':'등록 준비됨'}</p></div></div>`).join('')}<p class="muted field-help">등록 후 테스트 송장번호가 목록에 반영됩니다. 인쇄는 PDA 체크 시 별도로 요청됩니다.</p></div>`;$('#register-footer').innerHTML=`<button data-close="register-dialog">취소</button><button class="primary" id="register-start" ${invalid.length?'disabled':''}>${rows.length}건 등록하기</button>`;}
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
function progress(step){const labels=['전송 준비','대신 전산 등록','송장번호 반영'];$('#register-title').textContent='등록을 진행하고 있습니다';$('#register-content').innerHTML=`<div class="modal-content"><ol class="steps">${labels.map((text,i)=>`<li class="step ${i<step?'done':i===step?'current':''}"><b>${i<step?'✓':i+1}</b>${text}</li>`).join('')}</ol><p class="progress-copy"><span class="spinner"></span>${labels[step]} 중…</p><p class="muted">${reviewIds.length}건의 등록 흐름을 시뮬레이션하고 있습니다.</p></div>`;$('#register-footer').innerHTML='<button disabled>처리 중…</button>';}
function stamp(){return new Intl.DateTimeFormat('ko-KR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());}
function recordRegistration(rows,text){state.registrationLog.push({text,names:rows.map(r=>r.receiver).join(', '),time:stamp()});}
function completeRegistration(rows){for(const row of rows){if(row.status==='registered')continue;row.status='registered';row.waybill='DEMO-DS-'+String(state.serial++).padStart(4,'0');selected.delete(row.id);}recordRegistration(rows,'대신 '+rows.length+'건 등록완료 (모의)');render();}
async function runRegistration(){if(busy)return;const rows=reviewIds.map(find).filter(r=>r&&r.status==='ready');if(rows.length!==reviewIds.length||rows.some(validate)){toast('출고정보가 변경되었습니다. 다시 확인해 주세요.');renderReview();return;}busy=true;$('.close-modal[data-close="register-dialog"]').disabled=true;const scenario=$('#scenario').value;try{progress(0);await wait(550);if(scenario==='login'){$('#register-title').textContent='대신 로그인이 필요합니다';$('#register-content').innerHTML='<div class="modal-content"><div class="warning">대신 로그인 상태가 만료된 상황을 재현했습니다. 출고건은 등록하지 않았습니다.</div><p>실제 연동에서는 대신 사이트에 로그인한 후 다시 등록합니다.</p></div>';$('#register-footer').innerHTML='<button data-close="register-dialog">닫기</button><button id="simulate-login" class="primary">테스트 로그인 완료</button>';return;}rows.forEach(r=>{r.status='running';});persist();progress(1);await wait(750);if(scenario==='uncertain'){rows.forEach(r=>{r.status='uncertain';});recordRegistration(rows,'등록 응답 끊김 · 결과 확인 필요 (모의)');render();$('#register-title').textContent='등록 결과를 확인해야 합니다';$('#register-content').innerHTML='<div class="modal-content"><div class="warning">접수 요청 후 응답이 끊긴 상황입니다. 중복 등록을 막기 위해 다시 전송하지 않습니다.</div><p>목록의 <strong>등록 결과 확인</strong>을 누르면 먼저 등록된 결과를 조회해 반영하는 흐름을 체험할 수 있습니다.</p></div>';$('#register-footer').innerHTML='<button class="primary" data-close="register-dialog">목록에서 확인</button>';return;}progress(2);await wait(550);completeRegistration(rows);$('#register-title').textContent='대신 전산 등록 결과';$('#register-content').innerHTML=`<div class="modal-content"><div class="success-heading"><span class="success-icon">✓</span>${rows.length}건 등록완료</div><p class="muted">테스트 송장번호가 출고목록에 반영됐습니다.</p>${rows.map(r=>`<div class="review-row"><strong>${escapeHtml(r.receiver)}</strong><span class="waybill">${r.waybill}</span></div>`).join('')}<div class="connection">이제 해당 출고건의 PDA를 체크하면 모의 출력 요청이 남습니다.</div></div>`;$('#register-footer').innerHTML='<button data-close="register-dialog">닫기</button><button class="primary" id="view-registered">목록에서 PDA 체크하기</button>';$('#last-result').hidden=false;$('#last-result').innerHTML=`<span>✓ 대신 ${rows.length}건의 테스트 송장번호를 반영했습니다.</span><button id="view-log">등록 기록 보기</button>`;}finally{busy=false;$('.close-modal[data-close="register-dialog"]').disabled=false;$('#scenario').value='normal';renderList();}}
function reconcile(id){const row=find(id);if(!row||row.status!=='uncertain')return;completeRegistration([row]);toast('기존 등록 결과를 확인해 반영했습니다. 새 접수는 하지 않았습니다. (모의)');}
function openEdit(id,back=false){const row=find(id);if(!row)return;if(row.status!=='ready'){toast('이 테스트에서는 미등록 건만 수정할 수 있습니다.');return;}returnToReview=back;const form=$('#edit-form');['id','receiver','pay','qty','fare','address','postal'].forEach(name=>{field(form,name).value=row[name];});field(form,'qty').step=row.carrier==='로젠'?'1':'0.5';field(form,'qty').min=field(form,'qty').step;$('#edit-title').textContent=row.receiver+' 수정';$('#edit-dialog').showModal();}
function confirmReprint(rows){$('#confirm-copy').textContent=rows.length+'건은 이미 출력 요청한 이력이 있습니다. 같은 운송장번호로 다시 출력할까요?';$('#confirm-list').innerHTML=rows.map(r=>escapeHtml(r.receiver)+' · '+escapeHtml(r.waybill)).join('<br>');$('#confirm-dialog').showModal();return new Promise(resolve=>{confirmResolve=resolve;});}
function resolveConfirm(value){$('#confirm-dialog').close();const resolve=confirmResolve;confirmResolve=null;resolve?.(value);}
async function requestChecks(ids,kind){const rows=ids.map(find).filter(Boolean),newChecks=rows.filter(r=>!r.pda&&r.waybill&&r.status==='registered'),missing=rows.filter(r=>!r.pda&&!r.waybill),reprints=newChecks.filter(r=>r.prints>0);renderList();if(reprints.length&&!await confirmReprint(reprints))return;for(const row of newChecks){state.printLog.push({receiver:row.receiver,carrier:row.carrier,waybill:row.waybill,time:stamp(),reprint:row.prints>0});row.prints++;row.pda=true;}if(kind==='done')for(const row of rows)if(row.pda){row.done=true;row.waybillChecked=true;}render();toast((newChecks.length?newChecks.length+'건 모의 출력 요청을 남겼습니다.':'새롭게 PDA가 체크된 건이 없어 출력 요청하지 않았습니다.')+(missing.length?' 미등록 '+missing.length+'건은 제외했습니다.':''));}
function logenRate(qty,address,pay){return Number(qty)>0?Number(qty)*(pay==='선불'?3300:3500)+(/제주|서귀포/.test(address)?3000:0):'';}
function recalc(form,shipCarrier){const qty=field(form,'qty').value,pay=field(form,'pay').value,address=field(form,'address').value;if(shipCarrier==='로젠')field(form,'fare').value=logenRate(qty,address,pay);else if(Number(qty)>0){const parcel=field(form,'delivery')?.value==='택배',base=parcel?{'.5':6600,'0.5':6600,1:7150,2:14300}:{'0.5':4400,1:5500,2:11000};if(base[qty])field(form,'fare').value=base[qty];}}
function changeNewCarrier(next){if(next===newCarrier)return;newCarrier=next;const form=$('#new-form');form.classList.toggle('form-logen',next==='로젠');field(form,'qty').value=next==='로젠'?'1':'';field(form,'qty').step=next==='로젠'?'1':'0.5';field(form,'qty').min=field(form,'qty').step;field(form,'delivery').value=next==='로젠'?'택배':'정기';field(form,'delivery').disabled=next==='로젠';field(form,'fare').value=next==='로젠'?logenRate(1,field(form,'address').value,field(form,'pay').value):5500;$('#fare-help').textContent=next==='로젠'?'선불 3,300원 / 착불 3,500원 × 수량 · 제주 건당 +3,000원. 직접 수정 가능.':'수량과 운임을 직접 입력할 수 있습니다.';$$('[data-new-carrier]').forEach(b=>b.classList.toggle('active',b.dataset.newCarrier===next));$('.nav').classList.toggle('logen',next==='로젠');}
document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button||button.disabled)return;if(button.dataset.tab)navigate(button.dataset.tab);if(button.dataset.carrier){carrier=button.dataset.carrier;selected.clear();renderList();}if(button.dataset.newCarrier)changeNewCarrier(button.dataset.newCarrier);if(button.dataset.checkRow){const row=find(button.dataset.checkRow);if(row.pda&&row.waybillChecked&&row.done){row.pda=row.waybillChecked=row.done=false;render();}else void requestChecks([row.id],'done');}if(button.dataset.delete&&window.confirm('이 샘플 출고건을 삭제할까요?')){state.rows=state.rows.filter(r=>r.id!==button.dataset.delete);selected.delete(button.dataset.delete);render();}if(button.dataset.edit)openEdit(button.dataset.edit);if(button.dataset.reviewEdit){$('#register-dialog').close();openEdit(button.dataset.reviewEdit,true);}if(button.dataset.reconcile)reconcile(button.dataset.reconcile);if(button.dataset.close&&!busy){$('#'+button.dataset.close).close();returnToReview=false;}if(button.id==='register-start')void runRegistration();if(button.id==='simulate-login'){$('#scenario').value='normal';renderReview();}if(button.id==='view-registered'){$('#register-dialog').close();renderList();toast('등록한 거래처의 PDA를 체크해 보세요.');}if(button.id==='view-log')navigate('verify');});
$('#register-open').addEventListener('click',openRegistration);
$('#select-ready').addEventListener('click',()=>{selected=new Set(visible().filter(r=>r.carrier==='대신'&&r.status==='ready').map(r=>r.id));renderList();});
$('#select-all').addEventListener('change',event=>{for(const row of visible())event.target.checked?selected.add(row.id):selected.delete(row.id);renderList();});
$('#shipment-body').addEventListener('change',event=>{const el=event.target;if(el.dataset.select){el.checked?selected.add(el.dataset.select):selected.delete(el.dataset.select);renderList();}else if(el.dataset.pda){const row=find(el.dataset.pda);if(el.checked)void requestChecks([row.id],'pda');else{row.pda=false;render();}}else if(el.dataset.waybill){find(el.dataset.waybill).waybillChecked=el.checked;render();}else if(el.dataset.done){const row=find(el.dataset.done);if(el.checked)void requestChecks([row.id],'done');else{row.done=false;render();}}});
$('#all-pda').addEventListener('click',()=>{const rows=visible();if(rows.length&&rows.every(r=>r.pda)){rows.forEach(r=>r.pda=false);render();}else void requestChecks(rows.map(r=>r.id),'pda');});
$('#all-done').addEventListener('click',()=>{const rows=visible();if(rows.length&&rows.every(r=>r.done)){rows.forEach(r=>r.done=false);render();}else void requestChecks(rows.map(r=>r.id),'done');});
$('#all-waybill').addEventListener('click',()=>{const rows=visible(),next=!rows.every(r=>r.waybillChecked);rows.forEach(r=>r.waybillChecked=next);render();});
$('#check-everything').addEventListener('click',()=>void requestChecks(visible().map(r=>r.id),'done'));
$('#uncheck-everything').addEventListener('click',()=>{visible().forEach(r=>{r.pda=r.waybillChecked=r.done=false;});render();});
$('#confirm-no').addEventListener('click',()=>resolveConfirm(false));$('#confirm-yes').addEventListener('click',()=>resolveConfirm(true));$('#confirm-dialog').addEventListener('cancel',event=>{event.preventDefault();resolveConfirm(false);});
$('#register-dialog').addEventListener('cancel',event=>{if(busy)event.preventDefault();});
$('#date-form').addEventListener('submit',event=>{event.preventDefault();const start=$('#from-date').value,end=$('#to-date').value;if(start>end){toast('종료일은 시작일 이후로 선택해 주세요.');return;}from=start;to=end;selected.clear();renderList();});
$('#filter-today').addEventListener('click',()=>{from=to=today;$('#from-date').value=$('#to-date').value=today;selected.clear();renderList();});
$('#search').addEventListener('input',()=>{selected.clear();renderList();});$('#status-filter').addEventListener('change',()=>{selected.clear();renderList();});
$('#clear-filters').addEventListener('click',()=>{$('#search').value='';$('#status-filter').value='all';selected.clear();renderList();});
$('#edit-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,row=find(field(form,'id').value);if(!row||row.status!=='ready')return;for(const name of ['receiver','pay','address','postal'])row[name]=field(form,name).value.trim();row.qty=Number(field(form,'qty').value);row.fare=Number(field(form,'fare').value);$('#edit-dialog').close();render();if(returnToReview){returnToReview=false;renderReview();$('#register-dialog').showModal();}else toast('샘플 출고정보를 수정했습니다.');});
$('#edit-form').addEventListener('input',event=>{const row=find(field(event.currentTarget,'id').value);if(row?.carrier==='로젠'&&['qty','pay','address'].includes(event.target.name))recalc(event.currentTarget,'로젠');});
$('#new-form').addEventListener('input',event=>{if(['qty','pay','address','delivery'].includes(event.target.name))recalc(event.currentTarget,newCarrier);});
$('#toggle-date').addEventListener('click',()=>{const box=$('#new-date-box');box.hidden=!box.hidden;$('#toggle-date').setAttribute('aria-expanded',String(!box.hidden));});
$('#new-form').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget,get=name=>field(form,name).value.trim();if(newCarrier==='로젠'&&!Number.isInteger(Number(get('qty')))){toast('로젠 수량은 정수로 입력해 주세요.');return;}if(!/^\d{5}$/.test(get('postal'))){toast('우편번호를 숫자 5자리로 입력해 주세요.');return;}const date=$('#new-date').value||today;state.rows.unshift({id:crypto.randomUUID(),date,carrier:newCarrier,receiver:get('receiver'),sender:get('sender'),phone:get('phone'),address:get('address'),postal:get('postal'),pay:get('pay'),delivery:newCarrier==='로젠'?'택배':get('delivery'),qty:Number(get('qty')),fare:Number(get('fare')),status:'ready',waybill:'',pda:false,done:false,prints:0});persist();form.reset();$('#new-date').value=today;if(newCarrier==='로젠'){field(form,'qty').value='1';field(form,'fare').value='3500';field(form,'delivery').value='택배';}navigate('list');toast(date===today?'테스트 출고건을 추가했습니다.':dayLabel(date)+'에 저장했습니다. 조회기간을 해당 날짜로 바꾸면 볼 수 있습니다.');});
$('#reset-demo').addEventListener('click',()=>{if(!window.confirm('이 테스트 사이트의 샘플과 기록을 처음 상태로 되돌릴까요?'))return;state=initial();selected=new Set(['d1','d2']);carrier='전체';$('#search').value='';$('#status-filter').value='all';$('#scenario').value='normal';$('#last-result').hidden=true;render();navigate('list');toast('테스트를 처음 상태로 되돌렸습니다.');});
$('#today-label').textContent=dayLabel(today);$('#from-date').value=$('#to-date').value=$('#new-date').value=today;render();
